### ISSUE TITLE
追加課題

### ISSUE THREAD

**Issue by matsumoto777** [kmizuno1/Task2#1]
Training-2で下記の追加課題の実施をお願いします。

#### 1) 共通部品"LabelSwitch"を作成する

・レイアウトは下記の通り。
　| UILabel | UISwitch |
・UILabelとUISwitchの隙間は5とする。
・sizeThatFitsをオーバーライドする。ぴったりフィットする横幅を返す。
・LabelSwitchもlayoutSubviewsをオーバーライドして作ってください。

#### 2) Label1とButton1の間にSwitch1を配置する。

・Switch1の内容は下記の通り。
　Switch1 : LabelSwitchを使用する。Labelに"自動ログイン"を設定する。

・全体の並び方のイメージは下記の通り。
　｜Label1～～～ | Switch1｜Button1｜Button2｜Button3｜
　Switch1もログインボタン等と同様に右寄せとする。

・Switch1の横幅は、Switch1の内容にぴったりフィットする横幅とする。

**Comment by kmizuno1** [comment]
LabelSwitchを追加し、Switch1を実装しました。
