### ISSUE TITLE
LabelSwitchのlabelとSwitchの隙間

### ISSUE THREAD

**Issue by matsumoto777** [kmizuno1/Task2#2]
細かい話ですが
LabelSwitchのlayoutSubviewsを見ると、
labelとswitchの隙間が空いていません。

LabelSwitchのsizeThatFitsを使ってくれる間は問題が顕在化しませんが、
それよりも狭い幅で表示されたときに、labelとswitchがくっついてしまうかと思います。

**Comment by kmizuno1** [comment]
labelとswitchの隙間を設定しました。
