### ISSUE TITLE
ボタンを非表示にしたらその分詰めてください

### ISSUE THREAD

**Issue by matsumoto777** [kmizuno1/Task2#3]
ログインボタン、ログアウトボタン、非表示になったらその分を詰めるようにお願いします

**Comment by kmizuno1** [comment]
ログインボタン表示時と非表示字で隙間の幅を変更するようにしました。

**Comment by matsumoto777** [comment]
このコード、最低限の要求は満たせていると思いますが、
ログインボタンとログアウトボタンが「同時に表示する」もしくは「同時に表示しない」可能性を捨てているのですよね。

コードが縦に長いし２つの段落にわかれているのであまり見やすいともいえない。
変数nを経由することでframeのセット処理を共通化してますが、あまり見やすさに貢献していない。
if文の各ブロックにframeの設定処理を直接入れたほうが早いかもしれない。

でも、ログインボタン、ログアウトボタン関係なく各ボタンに対して機械的にisHiddenを判定していくのが一番シンプルで見やすいと思います。

**Comment by kmizuno1** [comment]
ログインボタン、ログアウトボタンそれぞれをisHiddenで判定するよう変更しました。

**Comment by matsumoto777** [comment]
ところで研修２に下記のように書いてあって、それが詰めることを意味しています。

```
※表示、非表示が切り替わったときでもスキマの10をキープするよう気をつけてください。
```

**Comment by matsumoto777** [comment]
OKです。
研修2完了です。
